allowBuilds:
  "@firebase/util": true
  "@google/genai": true
  "@sentry/cli": true
  protobufjs: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@firebase/util"
  - "@google/genai"
  - "@sentry/cli"
  - protobufjs
  - sharp
  - unrs-resolver

strictDepBuilds: false
